config/routes.rb
Rails.application.routes.draw do
  resources :brights
  get 'moon/gotohell'

  get 'moon/die'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
end

app/models/bright.rb
class Bright < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brights_controller.rb
class BrightsController < ApplicationController
  before_action :set_bright, only: [:show, :edit, :update, :destroy]

  # GET /brights
  # GET /brights.json
  def index
    @brights = Bright.all
  end

  # GET /brights/1
  # GET /brights/1.json
  def show
  end

  # GET /brights/new
  def new
    @bright = Bright.new
  end

  # GET /brights/1/edit
  def edit
  end

  # POST /brights
  # POST /brights.json
  def create
    @bright = Bright.new(bright_params)

    respond_to do |format|
      if @bright.save
        format.html { redirect_to @bright, notice: 'Bright was successfully created.' }
        format.json { render :show, status: :created, location: @bright }
      else
        format.html { render :new }
        format.json { render json: @bright.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brights/1
  # PATCH/PUT /brights/1.json
  def update
    respond_to do |format|
      if @bright.update(bright_params)
        format.html { redirect_to @bright, notice: 'Bright was successfully updated.' }
        format.json { render :show, status: :ok, location: @bright }
      else
        format.html { render :edit }
        format.json { render json: @bright.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brights/1
  # DELETE /brights/1.json
  def destroy
    @bright.destroy
    respond_to do |format|
      format.html { redirect_to brights_url, notice: 'Bright was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bright
      @bright = Bright.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bright_params
      params.require(:bright).permit(:name, :age, :address, :phone)
    end
end

app/controllers/moon_controller.rb
class MoonController < ApplicationController
  def gotohell
  end

  def die
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brights_helper.rb
module BrightsHelper
end

app/helpers/moon_helper.rb
module MoonHelper
end

app/views/brights/_form.html.erb
<%= form_with(model: bright, local: true) do |form| %>
  <% if bright.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bright.errors.count, "error") %> prohibited this bright from being saved:</h2>

      <ul>
      <% bright.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :bright_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age, id: :bright_age %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :bright_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :bright_phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brights/edit.html.erb
<h1>Editing Bright</h1>

<%= render 'form', bright: @bright %>

<%= link_to 'Show', @bright %> |
<%= link_to 'Back', brights_path %>

app/views/brights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brights</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brights.each do |bright| %>
      <tr>
        <td><%= bright.name %></td>
        <td><%= bright.age %></td>
        <td><%= bright.address %></td>
        <td><%= bright.phone %></td>
        <td><%= link_to 'Show', bright %></td>
        <td><%= link_to 'Edit', edit_bright_path(bright) %></td>
        <td><%= link_to 'Destroy', bright, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bright', new_bright_path %>

app/views/brights/new.html.erb
<h1>New Bright</h1>

<%= render 'form', bright: @bright %>

<%= link_to 'Back', brights_path %>

app/views/brights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bright.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @bright.age %>
</p>

<p>
  <strong>Address:</strong>
  <%= @bright.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @bright.phone %>
</p>

<%= link_to 'Edit', edit_bright_path(@bright) %> |
<%= link_to 'Back', brights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Persist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moon/die.html.erb
<h1>Moon#die</h1>
<p>Find me in app/views/moon/die.html.erb</p>

app/views/moon/gotohell.html.erb
<h1>Moon#gotohell</h1>
<p>Find me in app/views/moon/gotohell.html.erb</p>